ModelEngine-Group/nexent

backend/consts/model.py
frontend/app/chat/layout/chatLeftSidebar.tsx
frontend/app/chat/page.tsx
frontend/app/setup/layout/index.tsx
frontend/app/setup/modelSetup/appConfig.tsx
frontend/app/setup/modelSetup/config.tsx
frontend/app/setup/modelSetup/model/ModelListCard.tsx
frontend/app/setup/modelSetup/modelConfig.tsx
frontend/lib/avatar.tsx

🎨 Adjust the default color of the app icon
🐛 Optimize the loading timing of the model status
🐛 Bug fix: failed to load env config when entering /chat page

Bug fixes and icon style update on chat and setup page

---

backend/apps/agent_app.py
backend/apps/config_sync_app.py
backend/apps/elasticsearch_app.py
backend/utils/agent_utils.py
backend/utils/config_utils.py
backend/utils/file_management_utils.py

🚚 Move configManager to config_utils.py

🚚 Move configManager to config_utils.py

---

backend/consts/model.py
backend/database/client.py
frontend/server.js

🐛 Fix minio files cannot be accessed

🐛 Fix minio files cannot be accessed

---

backend/utils/agent_utils.py

🐛 Fix import path of config_manager

🐛 Fix import path of config_manager

---

docker/docker-compose.yml

🔨 update nexent images tag

---

docker/.env
make/Dockerfile
sdk/nexent/core/models/README.md
sdk/nexent/core/models/stt_model.py

🔨 Delete redundant environment variables

🔨 Delete redundant environment variables

---

README.md
README_CN.md
docker/.env.example
docker/deploy.sh
docker/docker-compose.yml

🔨 Update root path for docker volume

🔨 Update root path for docker volume

---

backend/agents/README.md
backend/prompts/README.md
sdk/nexent/core/agents/code_agent.py

📝 add agent&prompt README.md

---

frontend/app/setup/modelSetup/model/ModelAddDialog.tsx
frontend/app/setup/modelSetup/model/ModelDeleteDialog.tsx
frontend/app/setup/modelSetup/modelConfig.tsx

🔨 Optimize the logic of adding/deleting model by removing unnecessary model status check and redundant model list call, significantly shorten the response time

🔨 Optimize the logic of adding/deleting model

---

backend/database/conversation_db.py

🐛 fix conversation detail bug

---

make/base/Dockerfile
make/data_process/Dockerfile

🔨 Add proxy for pip install

---

backend/database/db_models.py
docker/init.sql

✨ Add data model for linguified Agent

✨ Add data model for linguified Agent

---

frontend/app/chat/streaming/chatStreamHandler.tsx
frontend/app/chat/streaming/chatStreamMain.tsx
frontend/app/chat/streaming/taskWindow.tsx

🐛 Fix handover conversation delay && Filter "thinking" output from llm

🐛 Fix handover conversation delay && Filter "thinking" output from llm

---

frontend/server.js

🐛 Fix the issue that the front - end port 3000 cannot be accessed normally outside the container.

🐛 Fix the issue that the front - end port 3000 cannot be accessed normally outside the container.

---

docker/uninstall.sh
test/test_agent_create_and_run.py

🔨 Add uninstall script

---

docker/uninstall.sh
make/main/Dockerfile

🔨 Adapt to ARM file permissions 022.

🔨 Adapt to ARM file permissions 022.

---

make/start.sh

🐛 Modify the startup working path to fix the file loading failure issue.

🐛 Modify the startup working path to fix the file loading failure issue.

---

make/data_process/Dockerfile

🔨 add nexent dependency for data_process

🔨 add nexent dependency for data_process

---

backend/apps/agent_app.py
backend/utils/agent_utils.py
sdk/nexent/core/agents/code_agent.py
sdk/pyproject.toml

🐛 fix conversation history bug

🐛 fix conversation history bug

---

docker/uninstall.sh

🔨 add nexent-web uninstall

---

frontend/app/setup/knowledgeBaseSetup/KnowledgeBaseManager.tsx
frontend/app/setup/knowledgeBaseSetup/document/DocumentContext.tsx
frontend/app/setup/knowledgeBaseSetup/document/DocumentListContainer.tsx
frontend/app/setup/knowledgeBaseSetup/document/DocumentListLayout.tsx
frontend/app/setup/knowledgeBaseSetup/knowledgeBase/KnowledgeBaseContext.tsx
frontend/app/setup/page.tsx
frontend/services/conversationService.ts
frontend/services/knowledgeBasePollingService.ts
frontend/services/knowledgeBaseService.ts

🐛 Fix bug: Document size and document status not properly updated
📝 Change knowledgeBase frontend comment to English 
🔨 Remove Knowledgebase cache preload logic

🐛 Fix bug: Document size and document status not properly updated

---

backend/requirements.txt
backend/services/data_process_service.py
frontend/app/setup/knowledgeBaseSetup/document/DocumentStatus.tsx
sdk/nexent/data_process/core.py
sdk/nexent/data_process/process_worker_pool.py

✨ Document process_worker_pool now use Ray to process by default, which increases the parallel processing capability of nexent.

✨ Document processer now supports Ray

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/improvement_proposal.yml

Add improvement template to allow developer to submit improvement proposals

✨ Add improvement template

---

frontend/lib/config.ts

🐛 fix bug: The model configuration information will be re-read after entering the page of knowledge base #143

---

frontend/app/chat/internal/chatInterface.tsx
frontend/app/chat/streaming/chatStreamMain.tsx
frontend/app/chat/streaming/taskWindow.tsx

Fix task detail hight auto resize #131

🐛 fix task detail hight auto resize #131

---

backend/apps/voice_app.py
frontend/app/chat/streaming/chatStreamFinalMessage.tsx
frontend/services/conversationService.ts

🐛 Restore the speech generation button and implement streaming output

---

frontend/app/chat/layout/chatLeftSidebar.tsx
frontend/app/chat/layout/chatRightPanel.tsx
frontend/app/chat/streaming/chatStreamFinalMessage.tsx
frontend/app/chat/streaming/chatStreamMessage.tsx

🐛 Bugfix #105  #112  #116  #200

🐛 Bugfix #112 #116 #200 #105

---

sdk/nexent/core/tools/exa_search_tool.py

🎨 Exa_Tool turns on image filtering by default. #176

---

frontend/app/chat/layout/chatLeftSidebar.tsx
frontend/app/chat/layout/chatRightPanel.tsx
frontend/components/ui/markdownRenderer.tsx
frontend/components/ui/scrollArea.tsx

🐛 Bugfix #220 Scroll bar automatically slides down #224 The citation corner mark disappears

---

frontend/app/setup/agentSetup/AgentConfig.tsx
frontend/app/setup/page.tsx

Agent configuration will be detected when click complete configuration. #179

---

backend/prompts/managed_system_prompt_template.yaml
backend/prompts/manager_system_prompt_template.yaml
backend/services/prompt_service.py

🐛 Fix the issue where Nexent gives irrelevant responses to questionslike "Who are you?"#134

---

backend/agents/create_agent_info.py
backend/apps/agent_app.py
backend/consts/model.py
backend/services/agent_service.py
frontend/app/setup/agentSetup/AgentManagementConfig.tsx
frontend/app/setup/agentSetup/ConstInterface.tsx
frontend/app/setup/agentSetup/components/AgentModal.tsx
frontend/services/agentConfigService.ts
frontend/services/api.ts
sdk/nexent/core/agents/agent_model.py
test/backend/services/test_agent_service.py

✨ Support sub agent import and export.

---

backend/database/agent_db.py
backend/database/db_models.py
backend/services/agent_service.py
docker/init.sql
frontend/app/setup/agentSetup/AgentManagementConfig.tsx
frontend/app/setup/agentSetup/ConstInterface.tsx
frontend/app/setup/agentSetup/components/AgentModal.tsx
frontend/services/agentConfigService.ts
frontend/types/agentAndToolConst.ts

#294 
pg数据库tool表新增is_available字段，如果工具被删除、mcp服务器切换、工具名称异常等情况，会在启动main_service的时候将工具设置成不可用的状态

✨ Tool adds an unavailable state. #294

---

frontend/app/chat/internal/chatInterface.tsx
frontend/app/chat/streaming/chatStreamFinalMessage.tsx
frontend/app/chat/streaming/chatStreamHandler.tsx
frontend/app/chat/streaming/taskWindow.tsx
frontend/app/setup/agentSetup/DebugConfig.tsx
frontend/components/ui/markdownRenderer.tsx

♻️ Show the code during debugging #278

---

frontend/app/setup/knowledgeBaseSetup/KnowledgeBaseManager.tsx

frontend issues fix
ix an issue where clicking "Create Knowledge Base" again causes an error.

✨ Support for Ray-Based Data Processing #273 frontend issues fix

---

backend/apps/tool_config_app.py
backend/main_service.py
backend/services/agent_service.py
backend/services/tool_configuration_service.py
test/backend/services/test_tool_configuration_service.py

启动main_service时会扫描工具和agent，之前是用类的构造方法自动执行，现在直接挪入main_service.py，更加直观的看到初始化时执行了哪些函数

🚚 init tool and agent when start main_service

---

frontend/app/setup/knowledgeBaseSetup/KnowledgeBaseManager.tsx
frontend/app/setup/knowledgeBaseSetup/components/UploadArea.tsx
frontend/app/setup/knowledgeBaseSetup/document/DocumentContext.tsx
frontend/app/setup/knowledgeBaseSetup/document/DocumentListContainer.tsx
frontend/app/setup/knowledgeBaseSetup/document/DocumentListLayout.tsx

✨ Support for Ray-Based Data Processing #273 --Add a loading indicator.

✨ Support for Ray-Based Data Processing #273 --Add a loading indicator.

---

frontend/app/setup/knowledgeBaseSetup/knowledgeBase/KnowledgeBaseList.tsx

✨ Support for Ray-Based Data Processing #273--bugs fix

---

frontend/app/setup/agentSetup/AgentManagementConfig.tsx

#317
For the current scenario, implement the following frontend modifications:
1. When a toolitem has isAvailable=false but isSelected=true, allow users to click to deactivate it.
2. When a toolitem has isAvailable=false and isSelected=false, display a disabled tooltip upon click.
Demo:
https://github.com/user-attachments/assets/b349f365-6b31-40cc-aeb7-9315df4bf954

🐛 Fix the issue where the enable/disable state of tools cannot be modified after they become unavailable. #317

---

docker/deploy.sh

🐛 Fix the issue that AK/SK cannot be generated properly in Windows environments when OpenSSL is not available. #333

🐛 Fix the issue that AK/SK cannot be generated properly in Windows environments when OpenSSL is not available. #333

---

backend/apps/README_CN.md
backend/apps/model_managment_app.py
backend/services/model_health_service.py
frontend/app/setup/modelSetup/model/ModelAddDialog.tsx
frontend/services/api.ts
frontend/services/modelService.ts

♻️ Add connectivity validation to custom models #62

---

backend/apps/data_process_app.py
backend/apps/elasticsearch_app.py
backend/apps/tenant_config_app.py
backend/consts/model.py
backend/data_process/app.py
backend/data_process/config.py
backend/data_process/utils.py
backend/data_process/worker.py
backend/database/db_models.py
backend/database/knowledge_db.py
backend/main_service.py
backend/services/data_process_service.py
backend/services/elasticsearch_service.py
backend/utils/file_management_utils.py
docker/init.sql
frontend/app/setup/knowledgeBaseSetup/KnowledgeBaseManager.tsx
frontend/services/knowledgeBasePollingService.ts

🐛 Fix data_process_service silently stuck with no response in specific situation.
♻️ Remove unexpected column knowledge_embedding_model, get such info from ElasticSearch interface.
♻️ Disentanglement file_management_utils and data_process_service, so that the nexent container no longer depends on pip packages in data_process container.

Celery bugs and other minor refactors

---

docker/init.sql
docker/sql/0619_add_tenant_config_t.sql

🔨 extract incremental SQL statements compared to v1.0.0.

---

backend/data_process/app.py
backend/data_process/config.py
backend/data_process/tasks.py
backend/services/data_process_service.py
backend/utils/config_utils.py
sdk/nexent/core/models/stt_model.py
sdk/nexent/core/models/tts_model.py

♻️ Shorten the info logging in data_process_service
♻️ Refactor the way to load environment variables: now directly get from docker envirnment, not from local .env files

Refactor the way to load environment variables

---

backend/utils/config_utils.py

🐛Regular users cannot save configurations #358

---

frontend/app/[locale]/chat/internal/chatInterface.tsx
frontend/app/[locale]/chat/internal/extractMsgFromHistoryResponse.tsx

🐛 Fixed a bug that could not switch historical conversations.

---

frontend/app/[locale]/layout.tsx
frontend/app/[locale]/page.tsx
frontend/components/providers/I18nProviderWrapper.tsx
frontend/components/providers/themeProvider.tsx

🐛 Fix the issue where the Chinese language is displayed after refreshing the English interface.

🐛 Fix the issue where the Chinese language is displayed after refreshing the English interface.

---

frontend/app/[locale]/chat/internal/chatInterface.tsx
frontend/app/[locale]/chat/internal/chatPreprocess.tsx

🐛 fix bug: upload file

---

backend/database/client.py
docker/.env.example
docker/docker-compose.prod.yml
docker/docker-compose.yml

🐛 Fix the issue of duplicate environment variable names.

---

.dockerignore
backend/apps/elasticsearch_app.py
backend/data_process/ray_actors.py
backend/data_process/tasks.py
backend/database/knowledge_db.py
backend/services/elasticsearch_service.py
backend/utils/config_utils.py
docker/deploy.sh
docker/uninstall.sh

✨ KnowledgeBase setup page now supports tenant-level separation
🐛 Bug fix: data process FORWARD task sometimes failed and stuck
🐛 Bug fix: uninstall incomplete; deploy not writing MINIO_KEY down
🐛 Bug fix: Flower sometimes start failed

✨ KnowledgeBase setup page now supports tenant-level separation

---

backend/nexent_mcp_service.py
backend/services/remote_mcp_service.py

1.当mcp成功挂载或卸载时，返回200
2.删除时应对网络波动，先清除PG数据，再执行卸载操作

🐛 fix bug: 1. add status_code when add/delete successfully 2. adjust the order of mcp deletion

---

backend/consts/model.py
backend/services/remote_mcp_service.py
frontend/app/[locale]/setup/agentSetup/components/McpConfigModal.tsx
frontend/public/locales/en/common.json
frontend/public/locales/zh/common.json
frontend/services/mcpService.ts
test/backend/app/test_remote_mcp_app.py
test/backend/services/test_remote_mcp_service.py

#443 #452
重新挂载后：
1.mcp连接添加超时异常
2.修复mcp_service日志名错误

✨ Check server mount status in the MCP configuration window.

---

backend/apps/config_sync_app.py

🐛 fix bug that cannot save config successfully

---

backend/apps/data_process_app.py
sdk/nexent/core/tools/knowledge_base_search_tool.py

🐛 Fix real-time file conversation function failed #504

---

frontend/components/ui/markdownRenderer.tsx
sdk/nexent/core/tools/knowledge_base_search_tool.py

🐛 Fixed the abnormal display of knowledge base source title

---

backend/apps/elasticsearch_app.py
backend/services/elasticsearch_service.py
sdk/nexent/core/models/embedding_model.py
sdk/nexent/vector_database/elasticsearch_core.py

#458
Knowledge base feature testing is as follows:

🎨[Improvement] Modification of the ES instance creation method, along with changes to the configuration approach.

---

frontend/app/[locale]/chat/streaming/chatStreamHandler.tsx

#433 In debug mode, there is a probability that the execution code will be incomplete.
修改前：
修改后：

🐛 In debug mode, there is a probability that the execution code will be incomplete.#433

---

.dockerignore
.gitignore
backend/apps/elasticsearch_app.py
backend/database/knowledge_db.py
backend/services/elasticsearch_service.py
docker/deploy.sh
docker/docker-compose.dev.yml
docker/docker-compose.prod.yml
docker/docker-compose.yml
frontend/app/[locale]/setup/knowledgeBaseSetup/components/UploadArea.tsx
frontend/app/[locale]/setup/knowledgeBaseSetup/components/UploadService.ts
frontend/public/locales/en/common.json
frontend/public/locales/zh/common.json
frontend/services/api.ts
frontend/services/knowledgeBaseService.ts
make/data_process/Dockerfile
make/main/Dockerfile

✨ Now KnowledgeBase page will automatically clean orphan kbs only exist in ElasticSearch or Postgres, keeping the cleanness of the database.
🐛 Bug fix: KnowledgeBase creation silently failed due to the name occupation by other tenants. 
♻️ Significantly improve the image building speed using uv pip cache. Now image nexent only cost 2s to build if the requirements unchanged.

🐛 Bug fix: KnowledgeBase creation silently failed due to the name occupation by other tenants. 

---

test/backend/app/test_agent_app.py

♻️ Developer testing pytest-ized for implementing real asynchronous functions: agent_app

♻️ Developer testing pytest-ized for implementing real asynchronous functions: agent_app

---

backend/apps/elasticsearch_app.py
frontend/app/[locale]/setup/knowledgeBaseSetup/components/UploadAreaUI.tsx

🐛 Bug fix: KnowledgeBase duplicate checking UI missing

🐛 Bug fix: KnowledgeBase duplicate checking UI missing

---

backend/services/agent_service.py
sdk/nexent/core/tools/knowledge_base_search_tool.py

Export failure in knowledge-base-equipped agents
Knowledge base retrieval tool returning content when no KB is selected #564 #557

🐛[release]Fixed two issues:Export failure in knowledge-base-equipped agents Knowledge base retrieval tool returning content when no KB is selected

---

backend/apps/config_sync_app.py
backend/consts/const.py
frontend/app/[locale]/setup/modelSetup/appConfig.tsx
frontend/app/[locale]/setup/page.tsx

#440 
1.如果未修改应用名称和应用描述，将不会保存，使用时加载默认值。用户切换中英文使用对应语言的名称和描述
2.修改应用描述的最大行数：12->15
3.应用名称不再是必填项

🐛 when user didn't edit app name or description, the corresponding information will not be saved

---

backend/agents/create_agent_info.py

🐛 agent name cannot be empty string when smolagents update to V1.14

---

.gitignore
backend/apps/data_process_app.py
backend/apps/elasticsearch_app.py
backend/consts/model.py
backend/data_process/app.py
backend/data_process/config.py
backend/data_process/ray_actors.py
backend/data_process/ray_config.py
backend/data_process/tasks.py
backend/data_process/worker.py
backend/data_process_service.py
backend/pyproject.toml
backend/services/data_process_service.py
backend/services/elasticsearch_service.py
backend/utils/file_management_utils.py
docker/deploy.sh
docker/docker-compose.prod.yml
frontend/next.config.mjs
frontend/services/api.ts
make/data_process/Dockerfile
make/main/Dockerfile
make/web/Dockerfile
test/backend/app/test_data_process_app.py
test/backend/app/test_elasticsearch_app.py
test/backend/services/test_data_process_service.py
test/backend/services/test_elasticsearch_service.py

🎨 Remove redundant parameter 'search_redis'
🎨 Clean up unused Celery task status
♻️ Rewritten init functions as class methods in RayConfig
♻️ Decouple Celery and main_service
✨ Optimize the CPU_cores x celery_concurrency allocation, transferring the concurrency decision right to ray not celery.  
✨ [WIP] Fully supports the auto on/off of the ray dashboard and celery flower

✨ Optimize the CPU_cores x celery_concurrency allocation

---

backend/apps/agent_app.py
backend/database/agent_db.py
backend/main_service.py
backend/services/agent_service.py
frontend/app/[locale]/chat/internal/chatInterface.tsx
frontend/app/[locale]/chat/layout/chatInput.tsx
frontend/app/[locale]/chat/streaming/chatStreamMain.tsx
frontend/components/ui/agentSelector.tsx
frontend/public/locales/en/common.json
frontend/public/locales/zh/common.json
frontend/services/agentConfigService.ts
frontend/services/api.ts
test/backend/app/test_agent_app.py

✨Support Agent switching at conversation start.

---

test/backend/app/test_agent_app.py
test/backend/services/test_agent_service.py

add 4 test case
Modify test cases corrupted due to ToolConfig class changes

[release]🧪 add test case to file agent_app.py and agent_service.py

---

test/backend/app/test_agent_app.py
test/backend/services/test_agent_service.py

add 4 test case
Modify test cases corrupted due to ToolConfig class changes

🧪 add test case to file agent_app.py and agent_service.py

---

frontend/app/[locale]/chat/streaming/chatStreamFinalMessage.tsx
frontend/app/[locale]/chat/streaming/chatStreamMessage.tsx

🐛[Bug] Fix the issue where the copy button fails #627

🐛[Bug] Fix the issue where the copy button fails #627

---

sdk/nexent/core/agents/core_agent.py

#618
smoalgents V1.14 移动了memory的保存逻辑
现在可以正常执行agent

[release]🐛 Agent step results not saved to memory.

---

backend/services/agent_service.py

🐛[Bug]Fix the issue of blank agents in the agent selection box on the conversation page #625

🐛[Bug]Fix the issue of blank agents in the agent selection box on the conversation page #625

---

backend/services/agent_service.py

#625 
Added logic to filter out agents with 'None' as their name

🐛[Bug] Fix the issue of blank agents in the agent selection box on the conversation page

---

backend/services/prompt_service.py
frontend/app/[locale]/setup/agentSetup/components/SystemPromptDisplay.tsx

🐛 modify the prompt generate display.

---

backend/services/prompt_service.py
docker/.env.beta
frontend/app/[locale]/setup/agentSetup/components/SystemPromptDisplay.tsx

[release]🐛 modify the prompt generate display.

---

frontend/app/[locale]/setup/modelSetup/appConfig.tsx

#610 
状态更新冲突：两个useEffect都在监听配置变化并重置本地状态
第一个监听configChanged事件
第二个监听appConfig属性变化
当用户输入时，这些更新会覆盖用户输入，导致光标跳转
异步更新竞态，onBlur时调用updateAppConfig可能触发异步配置更新
配置更新后通过事件或useEffect重新设置状态
造成用户删除的文字被"恢复"

[release]🐛 Fix for cursor offset issue in application name and description input fields

---

frontend/app/[locale]/chat/streaming/chatStreamHandler.tsx

🐛Fixed the issue where no title was generated when uploading images or files in conversations.

---

backend/services/agent_service.py

🐛Fixed the issue where importing the agent and incorrect userID writing caused display failure  #653
This issue occurred due to duplicate fetching of user_id and tenant_id, with the second attempt lacking authentication credentials.Verified in the commercial version – the import is now successful. Test results are as follows:
https://github.com/user-attachments/assets/32ef6858-30ec-41d2-8305-3fb17d564aff

🐛Fixed the issue where importing the agent and incorrect userID writing caused display failure 

---

.github/workflows/docker-build-push-mainland.yml
.github/workflows/docker-build-push-overseas.yml
.github/workflows/docker-deploy.yml
docker/deploy.sh

✨ add community deployment script with terminal container support.
1. Add community deployment script for easy setup.
2. Support one-click terminal container deployment. 
3. Add domestic mirror push script for China region.

✨ add community deployment script with terminal container support.

---

.github/workflows/docker-build-push-mainland.yml
.github/workflows/docker-build-push-overseas.yml
.github/workflows/docker-deploy.yml
docker/deploy.sh

🔨 add community deployment script with terminal container support.
1.Add community deployment script for easy setup.
2.Support one-click terminal container deployment. 
3.Add domestic mirror push script for China region.

🔨 add community deployment script with terminal container support.

---

backend/utils/langchain_utils.py

🐛Fix the issue where the LangChain tool fails to refresh properly due to incorrect path errors  #695

🐛Fix the issue where the LangChain tool fails to refresh properly due to incorrect path errors

---

backend/services/model_health_service.py
sdk/nexent/core/models/embedding_model.py
sdk/nexent/core/models/openai_llm.py
sdk/nexent/core/models/openai_vlm.py
test/backend/services/test_model_health_service.py
test/sdk/core/models/test_embedding_model.py
test/sdk/core/models/test_openai_llm.py
test/sdk/core/models/test_openai_vlm.py

🐛Convert the healthcheck for all models to run asynchronously #558

🐛Convert the healthcheck for all models to run asynchronously

---

backend/data_process_service.py

Close issue: #703 
Self-test screenshot：

🐛 Fix bug: Failed to create new knowledgebase due to ray cluster initialize failure

---

backend/agents/create_agent_info.py

🐛 fix bug Agent without MCP tools still presents Connecting to MCP

---

backend/agents/create_agent_info.py
frontend/app/[locale]/chat/layout/chatInput.tsx
frontend/app/[locale]/setup/agentSetup/components/AgentConfigurationSection.tsx
frontend/app/[locale]/setup/agentSetup/components/AgentSelector.tsx
frontend/app/[locale]/setup/agentSetup/components/PromptManager.tsx
frontend/public/locales/en/common.json
frontend/public/locales/zh/common.json

🐛 Select agent first and then have a conversation.

---

frontend/app/[locale]/setup/page.tsx

🐛 Fix bugs: configuration is not saved correctly.

---

test/backend/agents/test_create_agent_info.py
test/backend/services/test_agent_service.py

[release]🧪 Modify test cases

---

frontend/app/[locale]/setup/agentSetup/components/AgentConfigurationSection.tsx
frontend/public/locales/en/common.json
frontend/public/locales/zh/common.json

 🐛 Fix bug: Disable segment control during prompt generation

---

doc/docs/zh/user-guide/app-configuration.md
doc/docs/zh/user-guide/index.md
doc/docs/zh/user-guide/knowledge-base-configuration.md
doc/docs/zh/user-guide/model-configuration.md

Revise dead links in user-guide

Revise dead links in user-guide

---

docker/deploy.sh

#752 
- 优化了 openssh-server 在基础设施模式下的包含逻辑
- 改进提示信息： "Terminal tool enabled - openssh-server will be included in infrastructure"
- 新增终端工具可用性确认消息

🐛 修复部署脚本中的终端工具配置和基础设施服务

---

frontend/app/[locale]/chat/internal/chatInterface.tsx

**Changed timeout/controller setup**
- Only after obtaining a valid conversation_id should the AbortController and 120-second timeout be registered with conversationControllersRef/conversationTimeoutsRef to avoid accidental binding during the -1 phase and potentially terminating other conversations.
- Call resetTimeout() before processing the streaming response. During streaming, the timeout is renewed with each data: message that arrives. If no data arrives within 120 seconds, the current conversation is terminated and conversationService.stop is called.
- When ending/manually stopping the conversation, the controller and timeout for the conversation are cleaned up. The automatic stop after 120 seconds will no longer be triggered after the conversation ends.

🐛 Bugfix: Stop interface could be automatically triggered #700

---

docker/deploy.sh

 🐛 fix deploy.sh

---

.github/workflows/automic-unit-test.yml

🐛 fix the report not upload.

---

frontend/app/[locale]/chat/internal/memory/memoryManageModal.tsx
frontend/app/[locale]/layout.tsx
frontend/app/[locale]/setup/agentSetup/components/AgentSelector.tsx
frontend/app/[locale]/setup/agentSetup/components/CollaborativeAgentDisplay.tsx
frontend/app/[locale]/setup/agentSetup/components/PromptManager.tsx
frontend/app/[locale]/setup/agentSetup/components/SubAgentPool.tsx
frontend/app/[locale]/setup/agentSetup/components/ToolConfigModal.tsx
frontend/app/[locale]/setup/agentSetup/components/ToolPool.tsx
frontend/app/[locale]/setup/agentSetup/utils/agentUtils.ts
frontend/app/[locale]/setup/agentSetup/utils/toolUtils.ts
frontend/app/[locale]/setup/knowledgeBaseSetup/components/UploadArea.tsx
frontend/app/[locale]/setup/knowledgeBaseSetup/components/UploadService.ts
frontend/components/auth/registerModal.tsx
frontend/components/providers/rootProvider.tsx
frontend/hooks/useAuth.ts
frontend/hooks/useMemory.ts

Fix front-end warnings caused by Next js upgrade

🐛 Bugfix: Next js upgrade legacy issues

---

frontend/app/[locale]/setup/knowledgeBaseSetup/components/UploadArea.tsx
frontend/app/[locale]/setup/knowledgeBaseSetup/components/UploadAreaUI.tsx
frontend/app/[locale]/setup/knowledgeBaseSetup/document/DocumentListLayout.tsx

🎨 Fix lint warning in UploadArea.tsx, UploadAreaUI.tsx and DocumentListLayout.tsx, using a conciser tailwind style declaration
Solved #598

🐛 Fix bug: Some knowledgebase upload components misbehave when dragging file onto them

---

backend/apps/agent_app.py
backend/apps/memory_config_app.py
backend/services/agent_service.py
backend/services/memory_config_service.py
backend/utils/memory_utils.py
test/backend/app/test_agent_app.py
test/backend/services/test_agent_service.py

Delete associated memories when removing agent  #834
需要更完整的管理记忆生命周期: Agent 删除时需同步删除与其相关的记忆信息

🐛Delete associated memories when removing agent  #834

---

frontend/app/[locale]/setup/modelSetup/config.tsx
frontend/app/[locale]/setup/modelSetup/modelConfig.tsx
frontend/app/[locale]/setup/page.tsx
frontend/public/locales/en/common.json
frontend/public/locales/zh/common.json

🐛 Fix bug: warning modal cannot popup when embedding model is not selected

---

backend/apps/remote_mcp_app.py
frontend/services/api.ts

🐛 fix bug: 307 Temporary Redirect when post mcp/tools interface

---

frontend/app/[locale]/setup/agentSetup/AgentManagementConfig.tsx

🐛 Only get agent list once when entering the page of agent setup

---

make/terminal/Dockerfile

[release]🔨 Download correct miniconda software package when building terminal images

---

frontend/app/[locale]/setup/agentSetup/AgentConfig.tsx
frontend/app/[locale]/setup/agentSetup/AgentManagementConfig.tsx

#990 
This issue is caused by the reset of the business logic description area after switching states.
https://github.com/user-attachments/assets/46df03e7-3fe0-4f5a-8032-84623f5a09e1

🐛 fix bug: Agent Information Display Error During Creation/Viewing

---

backend/prompts/managed_system_prompt_template_en.yaml

🐛 fix bug: Unable to run agent when switched to English environment.

---

backend/services/elasticsearch_service.py
test/backend/services/test_elasticsearch_service.py

#1080 🐛 Resolve the /indices?include_stats=true interface error.

🐛 Resolve the /indices?include_stats=true interface error. #1080

---

frontend/app/[locale]/chat/components/chatInput.tsx
frontend/app/[locale]/chat/components/chatLeftSidebar.tsx
frontend/app/[locale]/chat/components/chatRightPanel.tsx
frontend/app/[locale]/chat/internal/chatAttachment.tsx
frontend/app/[locale]/chat/internal/chatHelpers.tsx
frontend/app/[locale]/chat/internal/chatInterface.tsx
frontend/app/[locale]/chat/internal/chatPreprocess.tsx
frontend/app/[locale]/chat/internal/extractMsgFromHistoryResponse.tsx
frontend/app/[locale]/chat/internal/memory/memoryDeleteModal.tsx
frontend/app/[locale]/chat/internal/memory/memoryManageModal.tsx
frontend/app/[locale]/chat/page.tsx
frontend/app/[locale]/chat/streaming/chatStreamFinalMessage.tsx
frontend/app/[locale]/chat/streaming/chatStreamHandler.tsx
frontend/app/[locale]/chat/streaming/chatStreamMain.tsx
frontend/app/[locale]/chat/streaming/chatStreamMessage.tsx
frontend/app/[locale]/chat/streaming/taskWindow.tsx
frontend/app/[locale]/layout.tsx

♻️ Refactor: Frontend code clean (/app/chat) #1037

---

backend/apps/conversation_management_app.py
backend/apps/data_process_app.py
backend/apps/elasticsearch_app.py
backend/services/conversation_management_service.py
backend/services/data_process_service.py
backend/services/elasticsearch_service.py
test/backend/app/test_conversation_management_app.py
test/backend/app/test_data_process_app.py
test/backend/app/test_elasticsearch_app.py
test/backend/services/test_conversation_management_service.py
test/backend/services/test_data_process_service.py
test/backend/services/test_elasticsearch_service.py

#1084 ♻️ Reconstruct the app layer and service layer to comply with the MVC three-layer architecture.
知识库文件上传接口测试：
批量处理文件：

♻️ Refactor the conversation_management_app&conversation_management_service&data_process_app&es

---

backend/apps/remote_mcp_app.py
backend/database/remote_mcp_db.py
backend/services/remote_mcp_service.py
frontend/services/mcpService.ts
test/backend/app/test_remote_mcp_app.py
test/backend/database/test_remote_mcp_db.py
test/backend/services/test_remote_mcp_service.py

♻️ refactor mcp app/service/db/test case

---

backend/data_process/ray_config.py

🐛 Fixed ray startup failure.

---

backend/apps/tool_config_app.py
backend/database/tool_db.py
backend/services/tool_configuration_service.py
frontend/services/mcpService.ts
test/backend/app/test_tool_config_app.py
test/backend/database/test_tool_db.py
test/backend/services/test_tool_configuration_service.py

♻️ refactor tool app/service/db/test case

---

backend/apps/file_management_app.py
backend/services/file_management_service.py
test/backend/app/test_file_management_app.py
test/backend/services/test_file_management_service.py

#1085 ♻️ Refactor the file_management.
文件upload、process接口：
storage接口：

♻️ Refactor the file_management.

---

frontend/app/[locale]/setup/agentSetup/components/agent/AgentCallRelationshipModal.tsx
frontend/types/agentConfig.ts

🐛 BUG修复 agent调用关系展示优化
优化2.自适应工具框宽度，并限制工具名展示最大字符数
3.工具框和agent框更具区分性
多工具展示这里还在讨论具体展示方案，先合入2，3需求完成

🐛 BUG修复 agent调用关系展示优化

---

backend/apps/mock_user_management_app.py
backend/apps/user_management_app.py
backend/consts/exceptions.py
backend/consts/model.py
backend/database/user_tenant_db.py
backend/services/user_management_service.py
frontend/components/auth/loginModal.tsx
frontend/components/auth/registerModal.tsx
frontend/services/authService.ts
frontend/services/sessionService.ts
frontend/types/auth.ts
test/backend/app/test_mock_user_management_app.py
test/backend/app/test_user_management_app.py
test/backend/database/test_remote_mcp_db.py
test/backend/database/test_user_tenant_db.py
test/backend/services/test_user_management_service.py

#1087 
Use unified JsonResponse format and http error codes.
#1135 
Use a blank string instead of None when configuring the tts/stt model.
#1140

♻️ refactor user_management_xxx.py

---

backend/apps/image_app.py
backend/services/image_service.py
test/backend/app/test_image_app.py
test/backend/services/test_image_service.py

#1086  ♻️ refactor image module.

♻️ refactor image module.

---

.cursor/rules/backend/app_layer_rules.mdc
.cursor/rules/backend/database_layer_rules.mdc
.cursor/rules/backend/service_layer_rules.mdc
.cursor/rules/english_comments.mdc
.cursor/rules/environment_variable.mdc
CLAUDE.md
sdk/nexent/core/agents/run_agent.py
test/sdk/core/agents/test_run_agent.py

The rules would be applied automatically during your chat with cursor.
You can directly check the rule usage for each chat dialog using cursor IDE >= 1.5.x
When using claude code you need to explicit calling the rules, for instance:
Instead of saying:
"Create an endpoint for user management"
You should say:
"Create a user management endpoint following our app layer rules"

🔨 Update mdc cursor rules and claude.md for backend

---

.github/workflows/auto-web-check-dev.yml
frontend/const/knowledgeBase.ts

🔨 Add auto web type check. #1164 
类型错误检查：
检查通过：

🔨 Add auto web type check.

---

docker/deploy.sh
docker/generate_env.sh

#1014 🐛 The default change of ENV is Y when deploying in Infrastructure mode.
Infrastructure模式下默认更换root目录下env文件：

🐛 The default change of ENV is Y when deploying in Infrastructure mode.

---

backend/apps/user_management_app.py
backend/services/user_management_service.py
frontend/components/auth/registerModal.tsx
test/backend/app/test_user_management_app.py
test/backend/services/test_user_management_service.py

The app layer returns to JsonResponse normally, and returns to HTTPexception abnormally.

♻️ Trans exception from format JSONResponse to format HTTPException in user_managerment_app.py

---

backend/database/user_tenant_db.py
backend/main_service.py
backend/services/tool_configuration_service.py
test/backend/database/test_user_tenant_db.py
test/backend/services/test_tool_configuration_service.py

在服务初始化时更新工具数据，保证所有的工具改动不需要用户手动刷新工具列表

♻️ Refresh the tool list when backend service is initialized #1250

---

sdk/nexent/core/agents/nexent_agent.py
sdk/nexent/core/utils/constants.py
test/sdk/core/agents/test_nexent_agent.py

🐛 When integrating the deep thinking model, the content of the think label in the final answer should be removed. #1254

🐛 When integrating the deep thinking model, the content of the think label in the final answer should be removed. #1254
