frontend/app/setup/page.tsx
sdk/pyproject.toml

🐛 Fix the issue Chat requests blocked by other API calls #108
1. Remove the healtyCheck scheduled task;
2. Trigger the healtyCheck task every time the Model Configuration page or Knowledge Base page is accessed.
3. mcp version fixed

🐛 Fix the issue Chat requests blocked by other API calls #108

---

frontend/app/setup/agentSetup/components/AdditionalRequestInput.tsx

After the prompt fine-tuning button is clicked, the user instruction is not displayed. #201
1.Optimized the user experience, when you click to send a fine-tuning command, the fine-tuning command will not be cleared.
Before:
Current:

🐛 Fix the issue After the prompt fine-tuning button is clicked, the user instruction is not displayed. #201

---

frontend/app/chat/internal/chatInterface.tsx

#157
Modify the image preview style in chat messages to match the style used in the chat input box (chatInput.tsx)
**Image preview rendering in current chat session：**
**Background-free image preview effect in chat history：**
**Image preview rendering in input box：**

🐛 Fix the issue where "background-free images display with a black background, making the top-right close button difficult to see" #157

---

backend/apps/config_sync_app.py
backend/apps/tenant_config_app.py
backend/database/tenant_config_db.py
backend/utils/config_utils.py
frontend/app/setup/knowledgeBaseSetup/KnowledgeBaseManager.tsx
frontend/services/userConfigService.ts

🐛Regular users cannot save configurations #358
"1. Model configuration and loading, only filter by tenant_id, remove the filtering of user_id
2. Null pointer fix"
3. Adjust the trigger logic of the "Save Configuration" button on knowledge base related pages
4.Modify some knowledge base related APIs
admin:
https://github.com/user-attachments/assets/68d9b31f-2c61-4d90-9606-8159190fb37f
user:
https://github.com/user-attachments/assets/688481c5-4c05-4652-b696-82f7f48000cc

🐛Regular users cannot save configurations #358

---

frontend/app/[locale]/chat/layout/chatLeftSidebar.tsx

#396 
当历史对话标题过长时，容器会被撑开，影响悬浮提示框的正常显示。从而无法修改历史对话标题和删除历史对话
主要修改：限制标题显示区域的最大宽度为 250px，过长会被截断，展示省略号

🐛 fix bug: the title of historical conversation cannot be modified and deleted.

---

backend/apps/config_sync_app.py
backend/apps/conversation_management_app.py
backend/apps/knowledge_app.py
backend/apps/knowledge_summary_app.py
backend/services/conversation_management_service.py
backend/services/elasticsearch_service.py

1. Modify the original model configuration that used os.getenv to read from the database instead.
2. However, for the creation of ES instances, retain the embedding model API key configuration in the environment variables.
Related interfaces test：

🐛[Bug] Some model configurations are still read from env

---

sdk/nexent/vector_database/elasticsearch_core.py

修复本地检索工具无法正常检索的bug，问题在于embedding之后es检索表达式不正确

[release]🐛 fix bug: elasticsearch cannot retrieve.

---

sdk/nexent/vector_database/elasticsearch_core.py

修复本地检索工具无法正常检索的bug，问题在于embedding之后es检索表达式不正确

🐛 fix bug: elasticsearch cannot retrieve.

---

frontend/app/[locale]/setup/agentSetup/AgentConfig.tsx
frontend/app/[locale]/setup/agentSetup/AgentManagementConfig.tsx

#506 🐛[Improvement] The tool should be automatically refresh when empty.
1、去除打印两次“工具列表已刷新”逻辑；
2、首次进入Agent配置页面获取工具列表为空时，调用/tool/scan_tool接口更新工具列表。
修改前：
修改后：

🐛The tool should be automatically refresh when empty #506

---

frontend/app/[locale]/setup/agentSetup/AgentManagementConfig.tsx
frontend/services/agentConfigService.ts

#641 🐛 创建子agent时，需要清空提示词内容
修改前：
修改后：

[release]🐛 创建子agent时，需要清空提示词内容 #641

---

frontend/app/[locale]/chat/internal/chatInterface.tsx
frontend/app/[locale]/chat/streaming/chatStreamMain.tsx

#706 🐛 Switching conversations don't automatically slide to the bottom.
自测结果：

[release]🐛 Switching conversations don't automatically slide to the bottom.

---

frontend/components/ui/markdownRenderer.tsx

**Root Cause:**
The ReactMarkdown components only handled paragraph, blockquote, and code elements, causing it to skip unconfigured elements like lists (li). This resulted in reference markers within these elements not being rendered correctly.
**Solution:**
Added list items and other relevant elements in the ReactMarkdown components.
#704 #734

🐛 Error in cite index rendering

---

frontend/app/[locale]/setup/agentSetup/components/AgentConfigurationSection.tsx
frontend/app/[locale]/setup/agentSetup/components/AgentSelector.tsx
frontend/app/[locale]/setup/agentSetup/components/PromptManager.tsx

#770
🐛 Problem Description
1. Stale content display: When switching between different prompt sections (duty, constraint, few-shots) using the segmented controller, the expand modal would show outdated content from the previously viewed section
2. Component reuse issues: The modal component was being reused with the same key, preventing proper reinitialization when switching between different content sections
3. Inconsistent save/cancel behavior: Both the close button and clicking outside the modal would save changes, providing no way to cancel edits

🐛 Fix expand modal state synchronization issues

---

docker/deploy.sh

🐛 Fix syntax error in deploy script

---

frontend/app/[locale]/setup/agentSetup/AgentConfig.tsx
frontend/app/[locale]/setup/agentSetup/AgentManagementConfig.tsx

#776 🐛 When the page is loaded for the first time, the Agent name should be displayed.
自验证结果：
1、自动回填Agent名称和Agent描述，简化用户操作：
2、英文界面同样适配：
3、问答界面展示Agent名称

🐛 When the page is loaded for the first time, the Agent name should be displayed.

---

backend/agents/create_agent_info.py
backend/apps/conversation_management_app.py
backend/prompts/utils/generate_title.yaml
backend/prompts/utils/generate_title_en.yaml
backend/services/conversation_management_service.py
backend/services/elasticsearch_service.py
backend/services/prompt_service.py
backend/utils/attachment_utils.py
backend/utils/prompt_template_utils.py
test/backend/services/test_conversation_management_service.py

Unify all prompt template reading functions into one.
Validations:
All prompt templates are used correctly (both en and zh), including generating title, generating prompt, analyzing file, summary knowledge, managed/manager agents.
#468

♻️ Unify all prompt template reading functions into one

---

backend/apps/file_management_app.py
backend/prompts/analyze_file.yaml
backend/prompts/analyze_file_en.yaml
backend/utils/attachment_utils.py
frontend/app/[locale]/setup/modelSetup/model/ModelEditDialog.tsx
frontend/app/[locale]/setup/page.tsx
frontend/components/auth/avatarDropdown.tsx
frontend/components/auth/sessionListeners.tsx
frontend/hooks/useAuth.ts
frontend/public/locales/en/common.json
frontend/public/locales/zh/common.json
frontend/services/memoryService.ts
sdk/nexent/core/models/openai_long_context_model.py
test/sdk/core/models/test_openai_long_context_model.py

问题现象：内容较多的文件均会返回token过多的报错
问题根因：在user prompt中重复添加了原始文本，导致截断策略未生效
修改内容：删除user prompt中的替换符，增加定位日志
验证截图：

🐛 Bugfix: When file length exceed limits, not trunctated properly #519

---

frontend/public/locales/en/common.json
frontend/public/locales/zh/common.json
test/backend/app/test_file_management_app.py

🐛 Additional bugfix: The conversation cannot be interrupted during file parsing #648
修复了一个国际化提示未展示问题

🐛 Additional bugfix: The conversation cannot be interrupted during file parsing #648

---

frontend/app/[locale]/setup/agentSetup/components/McpConfigModal.tsx
frontend/services/api.ts
frontend/services/mcpService.ts

#898 
The problem is that the mcp/healthcheck interface does not pass in the authentication information correctly.

🐛 fix bug: MCP status indicator stays green when mcp server is unavailable

---

frontend/app/[locale]/setup/agentSetup/components/McpConfigModal.tsx
frontend/services/api.ts
frontend/services/mcpService.ts

#898 
The problem is that the mcp/healthcheck interface does not pass in the authentication information correctly.

[release]🐛 fix bug: MCP status indicator stays green when mcp server is unavailable

---

backend/services/elasticsearch_service.py
docker/docker-compose.prod.yml
docker/docker-compose.yml
frontend/app/[locale]/setup/knowledgeBaseSetup/document/DocumentListLayout.tsx
frontend/app/[locale]/setup/knowledgeBaseSetup/knowledgeBase/KnowledgeBaseList.tsx
frontend/lib/utils.ts
sdk/nexent/vector_database/elasticsearch_core.py
test/sdk/vector_database/test_elasticsearch_core.py

#896 🐛 The creation time of documents in knowledge base is not correct.
一、修改方法：
1、PG数据库、es库存储时都默认存储UTC时区时间；
2、返回给前端时统一返回无时区时间戳，前端统一使用new Date(number)方法根据当前所在时区，将时间戳转换为对应时间展示。
二、验证结果：
知识库页面：
问答页面：

🐛 The creation time of documents in knowledge base is not correct #896

---

frontend/types/knowledgeBase.ts

#1007  🐛 After the date formatting function is adjusted, there are cases where the function is called but the input is incorrect.

🐛 After the date formatting function is adjusted, there are cases where the function is called but the input is incorrect. #1007

---

frontend/app/[locale]/chat/internal/chatInterface.tsx

问题背景：
原来的代码在用户点击点赞/点踩后，虽然会调用 API 更新数据库，但本地状态没有正确更新，导致切换对话再切回来时，UI 显示的是旧的状态。
修复逻辑：
当用户点击点赞/点踩后，本地状态没有正确更新，导致切换对话再切回来时，UI 显示的是旧的状态。现在当用户点击点赞/点踩时，不仅会更新数据库，还会正确更新本地状态中的 opinion_flag 字段。
验证截图：
点击两个踩后切换对话再切回当前对话，点踩效果显示正常

🐛 Keep the likes and dislikes after switching conversations #806

---

docker/deploy.sh

#1023 🐛 When a non-root user redeploys, an error is reported and folder permissions cannot be set. 
修改原因：非root用户非首次部署时终端提示权限修改报错，会干扰用户定位排查。
before:
after:

🐛 When a non-root user redeploys, an error is reported and folder permissions cannot be set. #1023

---

frontend/app/[locale]/setup/knowledgeSetup/config.tsx

[release]🐛 use translate key when embedding model mismatched

---

frontend/public/locales/en/common.json
frontend/public/locales/zh/common.json

🐛 Bug Fix: rebuild to fix-up some missing translations

🐛 Bug Fix: rebuild to fix-up some missing translations

---

docker/deploy.sh

#1077 
问题根因：在deploy.sh中秘钥的路径是硬编码或直接定义在当前目录下的，当ROOT_DIR由当前目录变更后，没有在新目录找到秘钥文件
修改内容：deploy.sh中定义秘钥路径时使用ROOT_DIR变量
验证截图：
部署无影响

🐛 Bugfix: Terminal tool cannot read the key files #1077

---

backend/database/tool_db.py
docker/deploy.sh
docker/docker-compose.prod.yml
docker/docker-compose.yml
docker/generate_env.sh
make/terminal/Dockerfile
make/terminal/entrypoint.sh
sdk/nexent/core/tools/terminal_tool.py
test/sdk/core/tools/test_terminal_tool.py

✨ The terminal tool supports password login #1052
terminal镜像登录方式改为用户名密码认证，并在deploy脚本中支持用户手动设置（默认用户root）
使用本地环境进行terminal操作
使用远端环境进行terminal操作

✨ The terminal tool supports password login #1052
